### PR TITLE
log: Reuse code from withLogger in With

### PR DESCRIPTION
**Pull request by tsenart**
A small code reuse change set following up the work from @ChrisHines in #28.

### CODE REVIEW

**Comment by ChrisHines** [comment]
LGTM.

Code readability is improved by centralizing the thread safety code and the explanatory comment.

Also, this change subtly improves correctness—even if that was not intended—by copying the backing array of the `keyvals` passed to `log.With`. Although I don't expect this to come up very often, the following code works after this change but would have produced unexpected results with the old code.

```go
keyvals := []interface{}{"key", "v1"}
logger = log.With(logger, keyvals...)
keyvals[1] = "v2"
logger.Log(keyvals...)
```

This introduces an additional allocation when creating the first `withLogger`, but the result is correct in the general case.

Can we add a test case for the above scenario as part of this PR?

**Comment by tsenart** [comment]
@ChrisHines: Added the test.

**Comment by ChrisHines** [comment]
LGTM (in case it wasn't obvious)

**Comment by peterbourgon** [comment]
> +12 -13

:sunglasses:

**Pull request merged**
